apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-domain-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        role: my-domain-role
    spec:
      containers:
      - name: my-domain-service-testing
        image: gcr.io/my-project/my-domain-service-testing
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /healthy
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthy
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 2